name: UAE Financial Insights
title: UAE Financial Insights
description: UAE Financial Insights delivers expert analysis and in-depth perspectives on the UAE financial landscape. Stay informed with reliable insights from official sources.
logo: assets/images/idnlogos.png
favicon: assets/images/techico.png
url: 'https://uaefinance.github.io'
baseurl: ''
google_analytics: ''
include:
  - _pages
permalink: '/:title/'
authors:
  uaefin:
    name: UAE Finance
    display_name: UAE Finance
    email: thedubailife@gmail.com
    twitter: ''
    description: "So, you need any financial insights for Dubai expats?"
    web: "https://uaefinance.github.io"
    gravatar: 2c7d99fe281ecd3bcd65ab915bac6dd5
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
paginate: 6
paginate_path: '/page:num/'
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
adsense: 'disabled'
adsense-data-ad-client: ''
adsense-data-ad-slot: ''
lazyimages: 'enabled'
exclude:
  - changelog.md
  - LICENSE.txt
  - README.md
  - Gemfile
  - Gemfile.lock
jekyll_admin:
  hidden_links:
    - datafiles
